### ISSUE TITLE
Could not load on paper spigot 1.15.2

### ISSUE THREAD

**Issue by alan67160** [FendiTony777/SystemInfo#1]
### Version:
```This server is running Paper version git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)```

### Error:
```17.02 15:52:16 [Server] ERROR Could not load 'plugins/SystemInfo-1.0.0.jar' in folder 'plugins'
17.02 15:52:16 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/thevipershow/systeminfo/SystemInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
17.02 15:52:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:352) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
17.02 15:52:16 [Server] INFO Caused by: java.lang.UnsupportedClassVersionError: me/thevipershow/systeminfo/SystemInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
17.02 15:52:16 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_222]
17.02 15:52:16 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_222]
17.02 15:52:16 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_222]
17.02 15:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
17.02 15:52:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
17.02 15:52:16 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
17.02 15:52:16 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
17.02 15:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.15.2.jar:git-Paper-105]
17.02 15:52:16 [Server] INFO ... 6 more
17.02 15:52:16 [Server] WARN Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
```

**Comment by FendiTony777** [comment]
The plugin was built with Java 11 , and the server you are using has Java 8. I'm sorry for this , I'll provide a newer version compiled with Java8. The plugins should work find except for that. Thanks for reporting

**Comment by alan67160** [comment]
Wow you reply is so quick, btw thanks for the help

**Comment by FendiTony777** [comment]
I'll now close the issue and as soon as I can I will publish the version with Java8 on Spigot probably.
